services:
  os2display.campaign.campaign_service:
    class: Os2Display\CampaignBundle\Service\CampaignService
    arguments: ['@service_container']
    tags:
      - { name: kernel.event_listener, event: os2display.core.pre_push_channels, method: prePushChannels }
      - { name: kernel.event_listener, event: os2display.core.pre_push_channel, method: prePushChannel }
      - { name: kernel.event_listener, event: os2display.core.post_push_channels, method: postPushChannels }
      - { name: kernel.event_listener, event: os2display.core.pre_push_screen_serialization, method: prePushScreenSerialization }

  os2display.campaign_manager:
    class: Os2Display\CampaignBundle\Service\CampaignManager
    arguments:
      - '@os2display.entity_service'
      - '@os2display.security_manager'
      - '@os2display.group_manager'
      - '@doctrine.orm.entity_manager'
      - '@os2display.entity_manager'

  os2display.campaign_edit_voter:
    class: Os2Display\CampaignBundle\Security\EditVoter
    # parent: os2display.edit_voter
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@security.access.decision_manager'
      - '@os2display.security_manager'
    # public: false
    tags:
      - { name: security.voter }

  os2display.campaign.service.api_data:
    class: Os2Display\CampaignBundle\Service\ApiDataService
    arguments:
      - '@doctrine.orm.entity_manager'

  os2display.campaign.subscriber.api_data:
    class: Os2Display\CampaignBundle\Event\ApiDataSubscriber
    arguments:
      - '@os2display.campaign.service.api_data'
    tags:
      - { name: kernel.event_subscriber }

  os2display.campaign.subscriber.roles:
    class: Os2Display\CampaignBundle\Event\RolesSubscriber
    tags:
      - { name: kernel.event_subscriber }

  os2display.campaign.subscriber.cleanup:
    class: Os2Display\CampaignBundle\Event\CleanupSubscriber
    arguments:
    - '@doctrine.orm.entity_manager'
    tags:
    - { name: kernel.event_subscriber }
